apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-api
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-api
  template:
    metadata:
      labels:
        app: metrics-api
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
      - name: metrics-api
        image: "{{ registry_url }}/{{ push_target_backend }}:{{ version_backend }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "64m"
          limits:
            memory: "128Mi"
            cpu: "128m"