namespace: dbs
redis:
  appName: redis
  image: redis:latest
  replicas: 1
  secretName: redis-secret
  configMapName: redis-config
  pvcName: redis-data-pvc
  pvName: redis-data-pv
  storage:
    size: 2Gi
    class: opt-storage
    folder: /opt/redis-data
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  password: xxxxx
  maxMemory: 200mb
allowedNamespace: erpnext # which namespace is allowed for this redis?