namespace: apps

# compatibility (from official helm chart)
nameOverride: ""
fullnameOverride: ""

certSecretName: cloudflare-origin-tls

nextcloud:
  appName: nextcloud
  image: nextcloud:31.0.8
  replicas: 2
  secretName: nextcloud-secret
  pvcName: nextcloud-data-pvc
  serviceName: nextcloud-service
  ingressName: nextcloud-ingress
  host: cloud.waldhauser.sk
  protocol: https
  trustedDomains: "cloud.waldhauser.sk localhost"
  datadir: "/var/www/html/data"  # explicit data directory
  php:
    memoryLimit: 512M
    uploadLimit: 10G
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 256m
  storage:
    size: 100Gi
    folder: /opt/nextcloud-storage
    class: opt-storage
  admin:
    user: admin
    password: default_password # change when deploying ;)
  redis:
    host: redis-service.apps.svc.cluster.local
    port: 6379
    secretName: redis-secret
  postgres:
    host: postgresql-service.apps.svc.cluster.local
    port: 5432
    secretName: postgresql-secret