apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-community.fullname" . }}
  labels:
    {{- include "rabbitmq-community.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.amqpPort }}
    targetPort: amqp
    name: amqp
  - port: {{ .Values.service.amqpSSLPort }}
    targetPort: amqp-ssl
    name: amqp-ssl
  - port: {{ .Values.service.managementPort }}
    targetPort: management
    name: management
  selector:
    {{- include "rabbitmq-community.selectorLabels" . | nindent 4 }}
